spring:
  profiles:
    active:
      - dev
---
spring:
  application:
    name: config-test-dev1
  profiles: dev
---
spring:
  application:
    name: config-test-default1
  profiles: default
---
spring:
  application:
    name: config-test-prod1
  profiles: prod
