spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  application:
    name: config-test-dev
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8002
spring:
  application:
    name: config-test-default
  profiles: beta
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
---
server:
  port: 8003
spring:
  application:
    name: config-test-prod
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
