spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: eureka

server:
  port: 8761

eureka:
#  server:
#    eviction-interval-timer-in-ms: 10000 #设置清理间隔时间10s
#    enable-self-preservation: true #是否打开保护模式，默认true
  instance:
    hostname: localhost #可为域名，能解析即可
#    hostname: ${spring.cloud.client.ip-address}
#    appname: ${spring.application.name}
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

